from basic import Basic as B

transitions = {
    B.PI: [B.PI],
    B.PI1: [B.PI1, B.PI],
    B.PI2: [B.PI2, B.PI],
    B.PI3: [B.PI3, B.PI],
    B.PIHAT3: [B.PIHAT3, B.PI3, B.PI],
    B.S: [B.S, B.SIGMA],
    B.S1: [B.S1, B.S, B.SIGMA],
    B.S2: [B.S2, B.S, B.SIGMA],
    B.QBAR: [B.QBAR, B.SIGMA],
    B.Q: [B.Q, B.QBAR, B.SIGMA],
    B.Q1: [B.Q1, B.Q, B.QBAR, B.SIGMA],
    B.Q2: [B.Q2, B.Q, B.QBAR, B.SIGMA],
    B.SBAR: [B.SBAR, B.PI3, B.PI, B.SIGMA],
    B.T: [B.T, B.SIGMA],
    B.SIGMA: [B.SIGMA],
    B.I: [B.I, B.IPRIME, B.JPRIME, B.J],
    B.J: [B.J],
    B.JBAR: [B.JBAR, B.PI3, B.PI],
    B.PHI: [B.PHI, B.PI3, B.PI],
    B.PSI: [B.PSI, B.PI3, B.PI],
    B.O: [B.O],
    B.OPRIME: [B.OPRIME, B.O],
    B.OHAT: [B.OHAT, B.O],
    B.N: [B.N, B.NBAR, B.O],
    B.N0: [B.N0, B.NBAR0, B.PI3, B.PI, B.O, B.NBAR],
    B.N1: [B.N1],
    B.N2: [B.N2, B.NBAR2, B.PI2, B.PI, B.O, B.NBAR],
    B.NBAR: [B.NBAR, B.O],
    B.NBAR0: [B.NBAR0, B.NBAR, B.O],
    B.NBAR1: [B.NBAR1, B.NBAR, B.O],
    B.NBAR2: [B.NBAR2, B.NBAR, B.O],
    B.A: [B.A, B.ABAR],
    B.ABAR: [B.ABAR],
    B.P1: [B.P1, B.PI3, B.PI],
    B.P2: [B.P2]
}
